use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Skill Workshop API",
        description = "REST API for the Skill Workshop Platform — workshop management, enrollment, payments, reviews, and more.",
        version = env!("CARGO_PKG_VERSION"),
    ),
    paths(
        crate::routes::auth::register,
        crate::routes::auth::login,
        crate::routes::auth::request_otp,
        crate::routes::auth::verify_otp,
        crate::routes::auth::session_handler,
        crate::routes::auth::logout,
        crate::routes::user::get_profile,
        crate::routes::user::update_profile,
        crate::routes::user::list_registrations,
        crate::routes::user::list_users,
        crate::routes::user::get_user,
        crate::routes::user::admin_update_user,
        crate::routes::user::admin_delete_user,
        crate::routes::workshop::create_workshop,
        crate::routes::workshop::list_workshops,
        crate::routes::workshop::get_workshop_by_slug,
        crate::routes::workshop::update_workshop,
        crate::routes::workshop::delete_workshop,
        crate::routes::workshop::add_workshop_image,
        crate::routes::workshop::remove_workshop_image,
        crate::routes::workshop::levels::create_level,
        crate::routes::workshop::levels::list_levels,
        crate::routes::workshop::levels::get_level,
        crate::routes::workshop::levels::rename_level,
        crate::routes::workshop::levels::delete_level,
        crate::routes::category::create_category,
        crate::routes::category::list_categories,
        crate::routes::category::get_category_by_slug,
        crate::routes::category::update_category,
        crate::routes::category::delete_category,
        crate::routes::enrollment::create_enrollment,
        crate::routes::enrollment::my_enrollments,
        crate::routes::enrollment::get_enrollment,
        crate::routes::payment::success_get,
        crate::routes::payment::success_post,
        crate::routes::payment::fail_get,
        crate::routes::payment::fail_post,
        crate::routes::payment::cancel_get,
        crate::routes::payment::cancel_post,
        crate::routes::payment::ipn_handler,
        crate::routes::payment::refund_handler,
        crate::routes::payment::get_invoice_url,
        crate::routes::review::create_review,
        crate::routes::review::list_reviews_for_workshop,
        crate::routes::review::get_review,
        crate::routes::review::update_review,
        crate::routes::review::approve_review,
        crate::routes::review::reject_review,
        crate::routes::review::delete_review,
        crate::routes::contact::submit_contact,
        crate::routes::contact::list_contacts,
        crate::routes::contact::mark_read_contact,
        crate::routes::contact::delete_contact,
        crate::routes::stats::platform_stats,
        crate::routes::stats::workshop_ratings,
    ),
    components(
        schemas(
            crate::routes::auth::RegisterRequest,
            crate::routes::auth::RegisterResponse,
            crate::routes::auth::LoginRequest,
            crate::routes::auth::LoginResponse,
            crate::routes::auth::RequestOtpRequest,
            crate::routes::auth::VerifyOtpRequest,
            crate::routes::auth::SessionResponse,
            crate::routes::auth::LogoutResponse,
            crate::routes::user::UserProfileResponse,
            crate::routes::user::UpdateProfileRequest,
            crate::routes::user::RegistrationResponse,
            crate::routes::user::AdminUpdateUserRequest,
            crate::routes::workshop::WorkshopResponse,
            crate::routes::workshop::WorkshopImageResponse,
            crate::routes::workshop::CreateWorkshopRequest,
            crate::routes::workshop::UpdateWorkshopRequest,
            crate::routes::workshop::AddImageRequest,
            crate::routes::workshop::levels::LevelResponse,
            crate::routes::workshop::levels::CreateLevelRequest,
            crate::routes::workshop::levels::RenameLevelRequest,
            crate::routes::category::CategoryResponse,
            crate::routes::category::CreateCategoryRequest,
            crate::routes::category::UpdateCategoryRequest,
            crate::routes::enrollment::CreateEnrollmentRequest,
            crate::routes::enrollment::CreateEnrollmentResponse,
            crate::routes::enrollment::EnrollmentResponse,
            crate::routes::payment::PaymentCallback,
            crate::routes::payment::RefundRequest,
            crate::routes::payment::PaymentResponse,
            crate::routes::payment::IpnResponse,
            crate::routes::payment::InvoiceResponse,
            crate::routes::review::CreateReviewRequest,
            crate::routes::review::UpdateReviewRequest,
            crate::routes::review::ReviewResponse,
            crate::routes::contact::SubmitContactRequest,
            crate::routes::contact::ListContactsQuery,
            crate::routes::contact::ContactResponse,
            crate::routes::stats::PlatformStatsResponse,
            crate::routes::stats::WorkshopRatingResponse,
        )
    ),
    tags(
        (name = "auth", description = "Authentication endpoints — register, login, OTP, session"),
        (name = "users", description = "User profile and admin user management"),
        (name = "workshops", description = "Workshop CRUD and image management"),
        (name = "levels", description = "Workshop difficulty levels"),
        (name = "categories", description = "Workshop categories"),
        (name = "enrollments", description = "Enrollment creation and listing"),
        (name = "payments", description = "Payment processing, IPN, refunds, invoices"),
        (name = "reviews", description = "Review creation, moderation, and management"),
        (name = "contacts", description = "Contact form submissions (public submit, admin management)"),
        (name = "stats", description = "Platform statistics and workshop ratings"),
    ),
)]
/// OpenAPI specification for the Skill Workshop Platform.
pub struct ApiDoc;
